# Generated by Django 5.0.6 on 2024-06-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_teg_articleteg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleteg',
            old_name='main',
            new_name='is_main',
        ),
    ]
